services:
  postgres:
    image: "postgres:latest"
    environment:
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_USER=${POSTGRES_USER}"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
  redis:
    image: "redis:latest"
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
  springboot:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: springboot
    depends_on:
      - postgres
      - redis
    ports:
      - "${SPRINGBOOT_PORT}:${SPRINGBOOT_PORT}"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    env_file:
      - .env
